version: '3.8'

services:
  api-postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "44321:5432"
    restart: always
  api-redis:
    image: redis:alpine
    container_name: redis-story
    expose:
      - 6379