version: '3.8'

services:
  api-postgres:
    image: postgres:14.0-alpine
    shm_size: 256M
    restart: always
    container_name: 'api-postgres'
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "44321:5432"